
-- Drop tables if re-running (safe for dev, remove in prod)
DROP TABLE IF EXISTS saved_colleges;
DROP TABLE IF EXISTS college_courses;
DROP TABLE IF EXISTS colleges;
DROP TABLE IF EXISTS users;

-- users table
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) UNIQUE NOT NULL,
  password TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW()
);

-- colleges table
CREATE TABLE colleges (
  id SERIAL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  location VARCHAR(100) NOT NULL,
  fees INTEGER NOT NULL,              -- annual fees in INR
  rating DECIMAL(2,1) NOT NULL,       -- out of 5
  placement_percentage INTEGER NOT NULL, -- 0-100
  established_year INTEGER,
  overview TEXT,
  image_url TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- college course table
CREATE TABLE college_courses (
  id SERIAL PRIMARY KEY,
  college_id INTEGER REFERENCES colleges(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL
);

-- saved colleges tablee
CREATE TABLE saved_colleges (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  college_id INTEGER REFERENCES colleges(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(user_id, college_id) -- prevent duplicates
);

-- indexes (for performance on frequently filtered columns)
CREATE INDEX idx_colleges_location ON colleges(location);
CREATE INDEX idx_colleges_fees ON colleges(fees);
CREATE INDEX idx_colleges_rating ON colleges(rating);
CREATE INDEX idx_saved_user ON saved_colleges(user_id);

-- seed data generated by chatgpt
-- 15 colleges
INSERT INTO colleges (name, location, fees, rating, placement_percentage, established_year, overview, image_url) VALUES
('Indian Institute of Technology, Bombay', 'Mumbai, Maharashtra', 220000, 4.9, 98, 1958, 'IIT Bombay is one of India''s premier engineering institutions, known for world-class research and industry connections.', 'https://images.unsplash.com/photo-1562774053-701939374585?w=400'),
('Indian Institute of Technology, Delhi', 'New Delhi', 210000, 4.8, 97, 1961, 'IIT Delhi offers cutting-edge programs and has strong ties with top global companies for placements.', 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=400'),
('BITS Pilani', 'Pilani, Rajasthan', 480000, 4.7, 95, 1964, 'BITS Pilani is a private institution famous for its practice school program and strong alumni network.', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400'),
('National Institute of Technology, Trichy', 'Tiruchirappalli, Tamil Nadu', 75000, 4.5, 92, 1964, 'NIT Trichy is consistently ranked among the top NITs with excellent academic standards and campus culture.', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400'),
('Vellore Institute of Technology', 'Vellore, Tamil Nadu', 195000, 4.3, 88, 1984, 'VIT is known for its campus facilities, diverse student body, and strong industry recruitment.', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400'),
('Delhi Technological University', 'New Delhi', 90000, 4.4, 90, 1941, 'DTU offers excellent engineering programs with strong placements in Delhi-NCR tech companies.', 'https://images.unsplash.com/photo-1597733336794-fe5e0a6df05e?w=400'),
('Manipal Institute of Technology', 'Manipal, Karnataka', 280000, 4.2, 85, 1957, 'MIT Manipal offers a vibrant campus life with good industry exposure and diverse course offerings.', 'https://images.unsplash.com/photo-1571260899304-425eee4c7efc?w=400'),
('PSG College of Technology', 'Coimbatore, Tamil Nadu', 65000, 4.3, 87, 1951, 'PSG Tech is one of Tamil Nadu''s top private colleges with strong industry collaborations.', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=400'),
('SRM Institute of Science and Technology', 'Chennai, Tamil Nadu', 175000, 4.0, 82, 1985, 'SRMIST has grown into a major university with broad academic offerings and multinational placements.', 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=400'),
('Thapar Institute of Engineering', 'Patiala, Punjab', 310000, 4.4, 89, 1956, 'Thapar is highly regarded for its tech programs and consistently delivers strong placement results.', 'https://images.unsplash.com/photo-1562774053-701939374585?w=400'),
('Amity University', 'Noida, Uttar Pradesh', 230000, 3.8, 78, 2005, 'Amity offers a wide range of programs with good campus infrastructure and industry tie-ups.', 'https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=400'),
('PES University', 'Bengaluru, Karnataka', 210000, 4.3, 91, 1972, 'PES University is a premier Bangalore institution with strong CSE placements in top IT companies.', 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=400'),
('RV College of Engineering', 'Bengaluru, Karnataka', 120000, 4.2, 87, 1963, 'RVCE is one of Bangalore''s oldest and most respected engineering colleges with excellent faculty.', 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400'),
('NIT Warangal', 'Warangal, Telangana', 70000, 4.6, 93, 1959, 'NIT Warangal is one of the best NITs, known for its strong academics and placement record.', 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=400'),
('Jadavpur University', 'Kolkata, West Bengal', 15000, 4.5, 89, 1906, 'Jadavpur University is a top government institution offering excellent education at very low cost.', 'https://images.unsplash.com/photo-1597733336794-fe5e0a6df05e?w=400');

-- courses for each college
INSERT INTO college_courses (college_id, name) VALUES
(1, 'B.Tech Computer Science'), (1, 'B.Tech Electrical'), (1, 'B.Tech Mechanical'), (1, 'M.Tech AI/ML'), (1, 'PhD Programs'),
(2, 'B.Tech Computer Science'), (2, 'B.Tech Civil'), (2, 'B.Tech Chemical'), (2, 'M.Tech Data Science'),
(3, 'B.E. Computer Science'), (3, 'B.E. Electronics'), (3, 'B.E. Mechanical'), (3, 'M.E. Software Systems'),
(4, 'B.Tech Computer Science'), (4, 'B.Tech Electronics'), (4, 'B.Tech Production'), (4, 'M.Tech VLSI'),
(5, 'B.Tech CSE'), (5, 'B.Tech IT'), (5, 'B.Tech Biomedical'), (5, 'MBA Tech'),
(6, 'B.Tech Software Engineering'), (6, 'B.Tech Electronics'), (6, 'B.Tech Information Technology'),
(7, 'B.Tech CSE'), (7, 'B.Tech Mechatronics'), (7, 'B.Tech Aeronautical'),
(8, 'B.E. CSE'), (8, 'B.E. EEE'), (8, 'B.E. Mechanical'), (8, 'M.E. Computer Science'),
(9, 'B.Tech CSE'), (9, 'B.Tech IT'), (9, 'B.Tech Aerospace'), (9, 'MBA'),
(10, 'B.E. CSE'), (10, 'B.E. ECE'), (10, 'B.E. Chemical'),
(11, 'B.Tech CSE'), (11, 'B.Tech Biotechnology'), (11, 'BBA'), (11, 'MBA'),
(12, 'B.Tech CSE'), (12, 'B.Tech ISE'), (12, 'B.Tech ECE'), (12, 'M.Tech CSE'),
(13, 'B.E. CSE'), (13, 'B.E. ECE'), (13, 'B.E. Civil'), (13, 'M.Tech'),
(14, 'B.Tech CSE'), (14, 'B.Tech ECE'), (14, 'B.Tech Mechanical'), (14, 'M.Tech'),
(15, 'B.E. CSE'), (15, 'B.E. Electrical'), (15, 'B.E. Civil'), (15, 'M.E. CSE'), (15, 'PhD');